name: Build nuGet Package

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  publish-nuget:
    name: Publish nuGet Package
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1 

      - name: Setup .NET
        uses: actions/setup-dotnet@v2     
        with:
          dotnet-version: 8.0.x
          source-url: https://nuget.pkg.github.com/zsolt3991/index.json
        env:        
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Restore dependencies
        run: dotnet restore WingetHelper

      - name: Build
        run: dotnet build WingetHelper --no-restore --configuration Release -p:Version=${{steps.tag.outputs.tag}}

      - name: Pack with dotnet
        run: dotnet pack WingetHelper --configuration Release -p:Version=${{steps.tag.outputs.tag}}

      - name: Push with dotnet
        run: dotnet nuget push "WingetHelper/bin/Release/*.nupkg" --skip-duplicate --no-symbols

      # Create the release:  
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        continue-on-error: true
        with:
          tag: ${{ steps.tag.outputs.tag }}
          name:  ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}

      # Upload release asset:  
      - name: Update release asset
        id: upload-release-asset
        uses: AButler/upload-release-assets@v2.0
        with: 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          release-tag: ${{ steps.tag.outputs.tag }}
          files: "WingetHelper/bin/Release/*.nupkg"