name: Build nuGet Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish-nuget:
    name: Publish nuGet Package
    runs-on: ubuntu-latest

    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2     
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/zsolt9331/index.json
        env:        
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Setup GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          configFilePath: GitVersion.yml
          updateprojectfiles: true
          updateassemblyinfo: false

      - name: Display Calculated Version
        run: |
          echo "SemVer: $GITVERSION_SEMVER"

      - name: Restore dependencies
        run: dotnet restore WingetHelper

      - name: Build
        run: dotnet build WingetHelper --no-restore --configuration Release -p:Version=$GITVERSION_SEMVER

      - name: Pack with dotnet
        run: dotnet pack WingetHelper --configuration Release

      - name: Push with dotnet
        run: dotnet nuget push "WingetHelper/bin/Release/*.nupkg" --skip-duplicate --no-symbols true
