name: Build nuGet Package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  publish-nuget:
    name: Publish nuGet Package
    runs-on: ubuntu-latest

    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2     
        with:
          dotnet-version: 6.0.x
          source-url: https://nuget.pkg.github.com/zsolt9331/index.json
        env:        
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
          additionalArguments: '/showConfig'
          configFilePath: GitVersion.yml
          updateAssemblyInfo: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release -p:Version=$SEMVER

      - name: Pack with dotnet
        run: dotnet pack --configuration Release

      - name: Push with dotnet
        run: dotnet nuget push "WingetHelper/bin/Release/*.nupkg" --skip-duplicate --no-symbols true
